version: '3.8'

services:
    frontend:
        build: weddingAppFrontEnd
        container_name: weddingAppFrontEnd
        depends_on: 
            - db
            - backend
        ports:
            - 80:80

    backend:
        build: weddingAppBackEnd
        container_name: weddingAppBackEnd
        depends_on:
            - db
        ports:
            - 8080:8080
        environment:
            # - "SPRING_PROFILES_ACTIVE=docker"
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wedding_app
            - SPRING_DATASOURCE_USERNAME=docker
            - SPRING_DATASOURCE_PASSWORD=docker
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        
    db:
        image: postgres:11.4
        container_name: db
        mem_limit: 512m
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_USER=docker
            - POSTGRES_DB=wedding_app
        command: postgres -c max_connections=300
        ports:
            - 5432:5432
        # volumes:
        #     -"./.data/postgres:/var/lib/postgres"
        
